version: '3'

services:

  php:
    container_name:  blank-console
    image:  soldatovdev/blank-console
    build:
      context: ./docker/dev/php
    env_file:
      - .env
    volumes:
      - .:/app
